//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gsoporte
{
    using System;
    using System.Collections.Generic;
    
    public partial class soporte
    {
        public int idSoporte { get; set; }
        public Nullable<int> idPerfil { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> idClasificacion { get; set; }
        public Nullable<int> idPrioridad { get; set; }
        public string Asunto { get; set; }
        public Nullable<decimal> HoraSoporte { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual clasificacion clasificacion { get; set; }
        public virtual estado estado { get; set; }
        public virtual perfil perfil { get; set; }
        public virtual prioridad prioridad { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
